export const DISTRICT_LIST_REQUEST = 'DISTRICT_LIST_REQUEST';
export const DISTRICT_LIST_SUCCESS = 'DISTRICT_LIST_SUCCESS';
export const DISTRICT_LIST_FAIL = 'DISTRICT_LIST_FAIL';

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAIL = 'GET_CITY_FAIL';