export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST';
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS';
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL';

export const PACKAGE_DETAILS_REQUEST = 'PACKAGE_DETAILS_REQUEST';
export const PACKAGE_DETAILS_SUCCESS = 'PACKAGE_DETAILS_SUCCESS';
export const PACKAGE_DETAILS_FAIL = 'PACKAGE_DETAILS_FAIL';

export const PACKAGE_CREATE_REQUEST = 'PACKAGE_CREATE_REQUEST';
export const PACKAGE_CREATE_SUCCESS = 'PACKAGE_CREATE_SUCCESS';
export const PACKAGE_CREATE_FAIL = 'PACKAGE_CREATE_FAIL';
export const PACKAGE_CREATE_RESET = 'PACKAGE_CREATE_RESET';

export const PACKAGE_REVIEW_CREATE_REQUEST = 'PACKAGE_REVIEW_CREATE_REQUEST';
export const PACKAGE_REVIEW_CREATE_SUCCESS = 'PACKAGE_REVIEW_CREATE_SUCCESS';
export const PACKAGE_REVIEW_CREATE_FAIL = 'PACKAGE_REVIEW_CREATE_FAIL';
export const PACKAGE_REVIEW_CREATE_RESET = 'PACKAGE_REVIEW_CREATE_RESET';

export const PACKAGE_UPDATE_REQUEST = 'PACKAGE_UPDATE_REQUEST';
export const PACKAGE_UPDATE_SUCCESS = 'PACKAGE_UPDATE_SUCCESS';
export const PACKAGE_UPDATE_FAIL = 'PACKAGE_UPDATE_FAIL';
export const PACKAGE_UPDATE_RESET = 'PACKAGE_UPDATE_RESET';

export const PACKAGE_DELETE_REQUEST = 'PACKAGE_DELETE_REQUEST';
export const PACKAGE_DELETE_SUCCESS = 'PACKAGE_DELETE_SUCCESS';
export const PACKAGE_DELETE_FAIL = 'PACKAGE_DELETE_FAIL';
export const PACKAGE_DELETE_RESET = 'PACKAGE_DELETE_RESET';

export const PACKAGE_CATEGORY_LIST_REQUEST = 'PACKAGE_CATEGORY_LIST_REQUEST';
export const PACKAGE_CATEGORY_LIST_SUCCESS = 'PACKAGE_CATEGORY_LIST_SUCCESS';
export const PACKAGE_CATEGORY_LIST_FAIL = 'PACKAGE_CATEGORY_LIST_FAIL';

export const PACKAGE_SUB_CATEGORY_LIST_REQUEST = 'PACKAGE_CATEGORY_LIST_REQUEST';
export const PACKAGE_SUB_CATEGORY_LIST_SUCCESS = 'PACKAGE_CATEGORY_LIST_SUCCESS';
export const PACKAGE_SUB_CATEGORY_LIST_FAIL = 'PACKAGE_CATEGORY_LIST_FAIL';

export const fAVORITE_LIST_REQUEST = 'FAVORITE_LIST_REQUEST';
export const fAVORITE_LIST_SUCCESS = 'FAVORITE_LIST_SUCCESS';
export const fAVORITE_LIST_FAIL = 'FAVORITE_LIST_FAIL';

export const SAVE_FAVORITE_REQUEST = 'SAVE_FAVORITE_REQUEST';
export const SAVE_FAVORITE_SUCCESS = 'SAVE_FAVORITE_SUCCESS';
export const SAVE_FAVORITE_FAIL = 'SAVE_FAVORITE_FAIL';
export const SAVE_FAVORITE_RESET = 'SAVE_FAVORITE_RESET';

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const GET_DATA_RESET = 'GET_DATA_RESET';