export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL';

export const PAYMENT_DETAILS_REQUEST = 'PAYMENT_DETAILS_REQUEST';
export const PAYMENT_DETAILS_SUCCESS = 'PAYMENT_DETAILS_SUCCESS';
export const PAYMENT_DETAILS_FAIL = 'PAYMENT_DETAILS_FAIL';

export const PAYMENT_CREATE_REQUEST = 'PAYMENT_CREATE_REQUEST';
export const PAYMENT_CREATE_SUCCESS = 'PAYMENT_CREATE_SUCCESS';
export const PAYMENT_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';
export const PAYMENT_CREATE_RESET = 'PAYMENT_CREATE_RESET';

export const PAYMENT_REVIEW_CREATE_REQUEST = 'PAYMENT_REVIEW_CREATE_REQUEST';
export const PAYMENT_REVIEW_CREATE_SUCCESS = 'PAYMENT_REVIEW_CREATE_SUCCESS';
export const PAYMENT_REVIEW_CREATE_FAIL = 'PAYMENT_REVIEW_CREATE_FAIL';
export const PAYMENT_REVIEW_CREATE_RESET = 'PAYMENT_REVIEW_CREATE_RESET';

export const PAYMENT_UPDATE_REQUEST = 'PAYMENT_UPDATE_REQUEST';
export const PAYMENT_UPDATE_SUCCESS = 'PAYMENT_UPDATE_SUCCESS';
export const PAYMENT_UPDATE_FAIL = 'PAYMENT_UPDATE_FAIL';
export const PAYMENT_UPDATE_RESET = 'PAYMENT_UPDATE_RESET';

export const PAYMENT_DELETE_REQUEST = 'PAYMENT_DELETE_REQUEST';
export const PAYMENT_DELETE_SUCCESS = 'PAYMENT_DELETE_SUCCESS';
export const PAYMENT_DELETE_FAIL = 'PAYMENT_DELETE_FAIL';
export const PAYMENT_DELETE_RESET = 'PAYMENT_DELETE_RESET';

export const PAYMENT_CATEGORY_LIST_REQUEST = 'PAYMENT_CATEGORY_LIST_REQUEST';
export const PAYMENT_CATEGORY_LIST_SUCCESS = 'PAYMENT_CATEGORY_LIST_SUCCESS';
export const PAYMENT_CATEGORY_LIST_FAIL = 'PAYMENT_CATEGORY_LIST_FAIL';

export const PAYMENT_SUB_CATEGORY_LIST_REQUEST = 'PAYMENT_CATEGORY_LIST_REQUEST';
export const PAYMENT_SUB_CATEGORY_LIST_SUCCESS = 'PAYMENT_CATEGORY_LIST_SUCCESS';
export const PAYMENT_SUB_CATEGORY_LIST_FAIL = 'PAYMENT_CATEGORY_LIST_FAIL';

export const fAVORITE_LIST_REQUEST = 'FAVORITE_LIST_REQUEST';
export const fAVORITE_LIST_SUCCESS = 'FAVORITE_LIST_SUCCESS';
export const fAVORITE_LIST_FAIL = 'FAVORITE_LIST_FAIL';

export const SAVE_FAVORITE_REQUEST = 'SAVE_FAVORITE_REQUEST';
export const SAVE_FAVORITE_SUCCESS = 'SAVE_FAVORITE_SUCCESS';
export const SAVE_FAVORITE_FAIL = 'SAVE_FAVORITE_FAIL';
export const SAVE_FAVORITE_RESET = 'SAVE_FAVORITE_RESET';