export const REPORT_LIST_REQUEST = 'REPORT_LIST_REQUEST';
export const REPORT_LIST_SUCCESS = 'REPORT_LIST_SUCCESS';
export const REPORT_LIST_FAIL = 'REPORT_LIST_FAIL';

export const REPORT_DETAILS_REQUEST = 'REPORT_DETAILS_REQUEST';
export const REPORT_DETAILS_SUCCESS = 'REPORT_DETAILS_SUCCESS';
export const REPORT_DETAILS_FAIL = 'REPORT_DETAILS_FAIL';

export const REPORT_DELETE_REQUEST = 'REPORT_DELETE_REQUEST';
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS';
export const REPORT_DELETE_FAIL = 'REPORT_DELETE_FAIL';
export const REPORT_DELETE_RESET = 'REPORT_DELETE_RESET';